---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: automate
    run_list:
      - recipe[automate::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver:
      vm_hostname: automate.local
      network:
        - ['private_network', {ip: '33.33.33.10'}]
      customize:
        memory: 2048
        cpus: 1
